### ISSUE TITLE
Requests for sql.js and codemirror.js yield HTML of main page

### ISSUE THREAD

**Issue by tvenable-mie** [mieweb/sqladmin#3]
The browser requests `client/compatibility/codemirror.js` and `client/compatibility/sql.js`, both of which just return the HTML for the main page again, resulting in JS syntax errors (because it's not JavaScript that's returned, it's HTML).

**Comment by wreiske** [comment]
Resolved by 0fa42f3b714f914b6ee19036b653297a5105be97
